apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: static-sites

resources:
  - k8s/product/deployment.yaml
  - k8s/product/service.yaml
  - k8s/solutions/deployment.yaml
  - k8s/solutions/service.yaml
  - k8s/hello-world/deployment.yaml
  - k8s/hello-world/service.yaml
  - k8s/homepage/deployment.yaml
  - k8s/homepage/service.yaml
  - k8s/networkpolicy.yaml

configMapGenerator:
  - name: product-html
    files:
      - index.html=sites/product/index.html
  - name: solutions-html
    files:
      - index.html=sites/solutions/index.html
  - name: hello-world-html
    files:
      - index.html=sites/hello-world/index.html
  - name: homepage-html
    files:
      - index.html=sites/homepage/index.html

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/part-of: static-sites
    includeSelectors: true
