apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - product/deployment.yaml
  - product/service.yaml
  - product/configmap.yaml
  - solutions/deployment.yaml
  - solutions/service.yaml
  - solutions/configmap.yaml
  - hello-world/deployment.yaml
  - hello-world/service.yaml
  - hello-world/configmap.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: static-sites
    includeSelectors: true
