apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - product/deployment.yaml
  - product/service.yaml
  - solutions/deployment.yaml
  - solutions/service.yaml
  - networkpolicy.yaml

namespace: default

commonLabels:
  app.kubernetes.io/part-of: static-sites
