apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-html
  namespace: static-sites
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Hello World</title>
      <style>
        body {
          font-family: sans-serif;
          background-color: #111;
          color: #00ffcc;
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
        }
      </style>
    </head>
    <body>
      <h1>Hello, World!</h1>
    </body>
    </html>
